Richie/kintegrate ios
kintegrate/kintegrate.dev pull request #26
Opened 2021-05-17 04:48 UTC by richiereitz

- Adds iOS starter page with a link to example project modeled after android starter
- Adds iOS tutorial page with a link to example project modeled after android tutorial

2021-05-17 05:13 UTC, beeman commented
Hi @richiereitz - thanks for the contribution! I will give it a spin tomorrow and let you know if I find anything that's off.

I just created a repo for the starter app, could you please push you sample app up there? Thanks!

2021-05-18 03:02 UTC, beeman requested changes
This looks good. Please address the repo url, and rebase to the latest `main` branch. Thanks!

2021-05-18 12:40 UTC, richiereitz commented on content/pages/starters/kin-ios-starter/index.md
> +2. Add the kin SDK to your [Podfile](https://github.com/richiereitz/kin-starter-ios/blob/main/Podfile)
Done!

2021-05-18 23:28 UTC, beeman approved these changes

2021-05-18 23:29 UTC, merged